### ISSUE TITLE
Allow for referencing other values with build-configs.yaml

### ISSUE THREAD

**Issue by opdavies** [opdavies/build-configs#4]
```yaml
parameters:
  drupal:
    docroot: web

  dockerfile:
    stages:
      build:
        extra_directories:
          - web/modules/custom
        commands:
          - composer validate
          - composer install
```

```yaml
parameters:
  drupal:
    docroot: web

  dockerfile:
    stages:
      build:
        extra_directories:
          - '%drupal.docroot%/modules/custom'
        commands:
          - composer validate
          - composer install
```
